version: "3.8"
services:
  token-api:
    environment:
      - HTTP_PORT=8080
      - RPC_URL=https://eth-mainnet.alchemyapi.io/v2/
    build:
      context: .
      dockerfile: docker/dockerfile.token-api
    ports:
      - "8080:8080"
    