// Code generated by MockGen. DO NOT EDIT.
// Source: backend-challenge-go/cmd/dao (interfaces: DaoInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	models "github.com/rarecircles/backend-challenge-go/cmd/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDaoInterface is a mock of DaoInterface interface.
type MockDaoInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDaoInterfaceMockRecorder
}

// MockDaoInterfaceMockRecorder is the mock recorder for MockDaoInterface.
type MockDaoInterfaceMockRecorder struct {
	mock *MockDaoInterface
}

// NewMockDaoInterface creates a new mock instance.
func NewMockDaoInterface(ctrl *gomock.Controller) *MockDaoInterface {
	mock := &MockDaoInterface{ctrl: ctrl}
	mock.recorder = &MockDaoInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDaoInterface) EXPECT() *MockDaoInterfaceMockRecorder {
	return m.recorder
}

// InsertTokens mocks base method.
func (m *MockDaoInterface) InsertTokens(arg0 models.Tokens) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTokens", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertTokens indicates an expected call of InsertTokens.
func (mr *MockDaoInterfaceMockRecorder) InsertTokens(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTokens", reflect.TypeOf((*MockDaoInterface)(nil).InsertTokens), arg0)
}

// GetTokens mocks base method.
func (m *MockDaoInterface) GetTokens(arg0 string) (models.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokens")
	ret0, _ := ret[0].(models.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokens indicates an expected call of GetTokens.
func (mr *MockDaoInterfaceMockRecorder) GetTokens(arg0 string) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokens", reflect.TypeOf((*MockDaoInterface)(nil).GetTokens))
}

// GetFirstToken mocks base method.
func (m *MockDaoInterface) GetFirstToken() (models.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstToken")
	ret0, _ := ret[0].(models.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFirstToken indicates an expected call of GetFirstToken.
func (mr *MockDaoInterfaceMockRecorder) GetFirstToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstToken", reflect.TypeOf((*MockDaoInterface)(nil).GetFirstToken))
}
