// Code generated by github.com/lightspeedretail/lsapi-platform/cmd/break-a-leg DO NOT EDIT.
package handler

import (
	"net/http"

	echo "github.com/labstack/echo/v4"
)

// HealthCheck health check route
func (h *Handlers) HealthCheck(ctx echo.Context) error {
	res := &echo.Map{"status": "OK"}

	return ctx.JSON(http.StatusOK, res)
}
