// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jose-camilo/backend-challenge-go/internal/pkg/search_engine (interfaces: SearchEngine)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	"github.com/degarajesh/backend-challenge-go/model"
	"github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockSearchEngine is a mock of SearchEngine interface
type MockSearcher struct {
	ctrl     *gomock.Controller
	recorder *MockSearcherMockRecorder
}

// MockSearchEngineMockRecorder is the mock recorder for MockSearchEngine
type MockSearcherMockRecorder struct {
	mock *MockSearcher
}

// NewMockSearchEngine creates a new mock instance
func NewMockSearchEngine(ctrl *gomock.Controller) *MockSearcher {
	mock := &MockSearcher{ctrl: ctrl}
	mock.recorder = &MockSearcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSearcher) EXPECT() *MockSearcherMockRecorder {
	return m.recorder
}

// Index mocks base method
func (m *MockSearcher) Index(arg0 context.Context, arg1 model.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Index", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Index indicates an expected call of Index
func (mr *MockSearcherMockRecorder) Index(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Index", reflect.TypeOf((*MockSearcher)(nil).Index), arg0, arg1)
}

// Search mocks base method
func (m *MockSearcher) Search(arg0 context.Context, arg1 string) ([]model.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", arg0, arg1)
	ret0, _ := ret[0].([]model.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search
func (mr *MockSearcherMockRecorder) Search(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSearcher)(nil).Search), arg0, arg1)
}